sudo: false
language: node_js
node_js:
  - "stable"
env:
#  global:
#    - BUILD_TIMEOUT=10000
script: node_modules/karma/bin/karma NODE_ENV=test start karma.conf.js --single-run
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install: npm install
