sudo: false
language: node_js
node_js:
  - "stable"
env:
#  global:
#    - BUILD_TIMEOUT=10000
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - rm -rf node_modules
install:
  - npm install -g firebase-tools
  - npm install
script: npm run build
after_success:
  - firebase deploy --token $FIREBASE_TOKEN
